name: country_info_picker
description: "Provides a country picker (name, flag, dial code, code, nationality, max length of phone number) for The Country Picker."
version: 0.0.5
homepage: https://github.com/mzzznn
repository: https://github.com/mzzznn/country_info_picker

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  assets:
    - assets/flags/
