name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'  # Corrected regex to properly capture semantic versioning tags

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Specify the Flutter version if needed, or use 'stable'

      - name: Install dependencies
        run: flutter pub get
        env:
          PUB_CACHE: /home/runner/.pub-cache

      - name: Publish (dry run)
        run: flutter pub publish --dry-run
        env:
          PUB_CACHE: /home/runner/.pub-cache
