name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'  # Ensure your regex is correctly capturing the intended tags

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: dart-lang/setup-dart@v1.2  # Use the setup-dart action to install Dart SDK
        with:
          flutter-version: 'stable'  # Specify the Flutter version if needed, or use 'stable'

      - name: Install dependencies
        run: flutter pub get
        env:
          PUB_CACHE: /home/runner/.pub-cache

      - name: Publish
        run: flutter pub publish --dry-run
        env:
          PUB_CACHE: /home/runner/.pub-cache
