name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: packages/country_info_picker

      - name: Publish
        run: flutter pub publish --dry-run
        working-directory: packages/country_info_picker
        env:
          PUB_TOKEN: ${{ secrets.PUB_TOKEN }}