name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Corrected regex for version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1.2

      - name: Run pub get and publish
        run: |
          dart pub get
          dart pub publish --dry-run
        working-directory: ./packages/country_info_picker
        env:
          PUB_CACHE: /home/runner/.pub-cache
